[project]
name = "mosaicml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hydra-core>=1.3.2",
    "optuna>=4.3.0",
    "scikit-learn>=1.7.0",
    "scikit-optimize>=0.10.2",
]
