# @package models.random_forest
_target_: sklearn.ensemble.RandomForestClassifier
param_space:
  n_estimators:
    - 50
    - 100
    - 200
  max_depth:
    - 3
    - 5
    - null
  criterion:
    - gini
    - entropy