_target_: sklearn.model_selection.RandomizedSearchCV
param_space_arg: param_distributions
n_iter: 20
cv: 5
verbose: 2
random_state: 42
n_jobs: -1
refit: True
error_score: 'raise'
return_train_score: True
scoring: 'accuracy'
